[General]
logLevel = 0 # 0 trace; 1 debug; 2 info

[showStats]
name = true
race = true
level = true
perkCount = true
height = false
equipedWeight = true
weight = true
armor = true
damage = false
skillTrainingsThisLevel = true
health = true
healthRate = false
healthRateMult = false
magicka = true
magickaRate = false
magickaRateMult = false
stamina = true
staminaRate = false
staminaRateMult = false
resistDamage = false
resistDisease = true
resistPoison = true
resistFire = true
resistShock = true
resistFrost = true
resistMagic = true
oneHanded = true
twoHanded = true
archery = true
block = true
smithing = true
heavyArmor = true
lightArmor = true
pickpocket = true
lockpicking = true
sneak = true
alchemy = true
speech = true
enchanting = true
alteration = true
conjuration = true
destruction = true
illusion = true
restoration = true
oneHandedPowerMod = false
twoHandedPowerMod = false
archeryPowerMod = false
blockPowerMod = false
smithingPowerMod = false
heavyArmorPowerMod = false
lightArmorPowerMod = false
pickpocketPowerMod = false
lockpickingPowerMod = false
sneakPowerMod = false
alchemyPowerMod = false
speechPowerMod = false
enchantingPowerMod = false
alterationPowerMod = false
conjurationPowerMod = false
destructionPowerMod = false
illusionPowerMod = false
restorationPowerMod = false
speedMult = true
inventoryWeight = true
carryWeight = true
criticalChance = true
meleeDamage = false
unarmedDamage = false
absorbChance = true
weaponSpeedMult = true
bowSpeedBonus = true
shoutRecoveryMult = false
movementNoiseMult = true
dragonSouls = true
combatHealthRegenMultiply = false
attackDamageMult = false
beast = false
xp = false

[showStatsName]
name = "Name"
race = "Race"
level = "Level"
perkCount = "Open Perks"
height = "Height"
equipedWeight = "Equiped Weight"
weight = "Weight"
armor = "Armor"
damage = "Damage"
skillTrainingsThisLevel = "Traings This Level"
health = "Health"
healthRate = "Health Rate"
healthRateMult = "Health Rate Multi"
magicka = "Magicka"
magickaRate = "Magicka Rate"
magickaRateMult = "Magicka Rate Multi"
stamina = "Stamina"
staminaRate = "Stamina Rate"
staminaRateMult = "Stamina Rate Multi"
resistDamage = "Resist Damage"
resistDisease = "Resist Disease"
resistPoison = "Resist Poison"
resistFire = "Resist Fire"
resistShock = "Resist Shock"
resistFrost = "Resist Frost"
resistMagic = "Resist Magic"
oneHanded = "One Handed"
twoHanded = "Two Handed"
archery = "Archery"
block = "Block"
smithing = "Smithing"
heavyArmor = "Heavy Armor"
lightArmor = "Light Armor"
pickpocket = "Pickpocket"
lockpicking = "Lockpicking"
sneak = "Sneak"
alchemy = "Alchemy"
speech = "Speech"
enchanting = "Enchanting"
alteration = "Alteration"
conjuration = "Conjuration"
destruction = "Destruction"
illusion = "Illusion"
restoration = "Restoration"
oneHandedPowerMod = "One Handed Mod"
twoHandedPowerMod = "Two Handed Mod"
archeryPowerMod = "Archery Mod"
blockPowerMod = "Block Mod"
smithingPowerMod = "Smithing Mod"
heavyArmorPowerMod = "Heavy Armor Mod"
lightArmorPowerMod = "Light Armor Mod"
pickpocketPowerMod = "Pickpocket Mod"
lockpickingPowerMod = "Lockpicking Mod"
sneakPowerMod = "Sneak Mod"
alchemyPowerMod = "Alchemy Mod"
speechPowerMod = "Speech Mod"
enchantingPowerMod = "Enchanting Mod"
alterationPowerMod = "Alteration Mod"
conjurationPowerMod = "Conjuration Mod"
destructionPowerMod = "Destruction Mod"
illusionPowerMod = "Illusion Mod"
restorationPowerMod = "Restoration Mod"
speedMult = "Speed"
inventoryWeight = "Inventory Weight"
carryWeight = "Carry Weight"
criticalChance = "Crit. Chance"
meleeDamage = "Melee Damage"
unarmedDamage = "Unarmed Damage"
absorbChance = "Magic Absorb"
weaponSpeedMult = "Weapon Speed"
bowSpeedBonus = "Bow Speed Bonus"
shoutRecoveryMult = "Shout Recovery Multi"
movementNoiseMult = "Noise Reduction"
dragonSouls = "Dragon Souls"
combatHealthRegenMultiply = "Combat Health Regen Multi"
attackDamageMult = "Attack Multi"
beast = "Beast"
xp = "XP"