[General]
logLevel = 2 # 0 trace; 1 debug; 2 info
closeOnOtherMenuOpen = true
showFactionMenu = false #WIP, factions and thanes should work
openFactionMenuButton = 9 #https://www.creationkit.com/index.php?title=Input_Script (dec values)

[showFactions]
showFactions = true
showThane = true
showChampion = true

[showBeastName]
vampire = "Vampire"
werewolf = "Werewolf"

[showStats]
name = true
race = true
level = true
perkCount = true
height = false
equipedWeight = false
weight = false
armor = true
damage = true 
skillTrainingsThisLevel = true
health = true
healthRatePer = true
magicka = true
magickaRatePer = true
stamina = true
staminaRatePer = true
resistDamage = false 
resistDisease = true
resistPoison = true
resistFire = true
resistShock = true
resistFrost = true
resistMagic = true
oneHanded = true
twoHanded = true
archery = true
block = true
smithing = true
heavyArmor = true
lightArmor = true
pickpocket = true
lockpicking = true
sneak = true
alchemy = true
speech = true
enchanting = true
alteration = true
conjuration = true
destruction = true
illusion = true
restoration = true
oneHandedPowerMod = false
twoHandedPowerMod = false
archeryPowerMod = false
blockPowerMod = false
smithingPowerMod = false
heavyArmorPowerMod = false
lightArmorPowerMod = false
pickpocketPowerMod = false
lockpickingPowerMod = false
sneakPowerMod = false
alchemyPowerMod = false
speechPowerMod = false
enchantingPowerMod = false
alterationPowerMod = false
conjurationPowerMod = false
destructionPowerMod = false
illusionPowerMod = false
restorationPowerMod = false
speedMult = true
inventoryWeight = true
carryWeight = true
criticalChance = true
meleeDamage = false
unarmedDamage = false
absorbChance = true
weaponSpeedMult = true
bowSpeedBonus = false
shoutRecoveryMult = true
movementNoiseMult = true #(1 = no reduction, 0 = 100% reduction)
dragonSouls = true
combatHealthRegenMultiply = false
attackDamageMult = true
beast = true
xp = true
reflectDamage = false
oneHandedMod = true
twoHandedMod = true
archeryMod = true
blockMod = true
smithingMod = true
heavyArmorMod = true
lightArmorMod = true
pickpocketMod = true
lockpickingMod = true
sneakMod = true
alchemyMod = true
speechMod = true
enchantingMod = true
alterationMod = true
conjurationMod = true
destructionMod = true
illusionMod = true
restorationMod = true
damageArrow = true
damageLeft = true
leftWeaponSpeedMult = true
rightItemCharge = false
leftItemCharge = false
armorPerks = true
mass = false
bowStaggerBonus = false
bypassVendorKeywordCheck = false
bypassVendorStolenCheck = false

[showStatsName]
name = "Name"
race = "Race"
level = "Level"
perkCount = "Open Perks"
height = "Height"
equipedWeight = "Equiped Weight"
weight = "Weight"
armor = "Armor"
damage = "Damage Weapon"
skillTrainingsThisLevel = "Trainings This Level"
health = "Health"
healthRatePer = "Health Rate"
magicka = "Magicka"
magickaRatePer = "Magicka Rate"
stamina = "Stamina"
staminaRatePer = "Stamina Rate"
resistDamage = "Resist Damage"
resistDisease = "Resist Disease"
resistPoison = "Resist Poison"
resistFire = "Resist Fire"
resistShock = "Resist Shock"
resistFrost = "Resist Frost"
resistMagic = "Resist Magic"
oneHanded = "One Handed"
twoHanded = "Two Handed"
archery = "Archery"
block = "Block"
smithing = "Smithing"
heavyArmor = "Heavy Armor"
lightArmor = "Light Armor"
pickpocket = "Pickpocket"
lockpicking = "Lockpicking"
sneak = "Sneak"
alchemy = "Alchemy"
speech = "Speech"
enchanting = "Enchanting"
alteration = "Alteration"
conjuration = "Conjuration"
destruction = "Destruction"
illusion = "Illusion"
restoration = "Restoration"
oneHandedPowerMod = "One Handed Power Mod"
twoHandedPowerMod = "Two Handed Power Mod"
archeryPowerMod = "Archery Power Mod"
blockPowerMod = "Block Power Mod"
smithingPowerMod = "Smithing Power Mod"
heavyArmorPowerMod = "Heavy Armor Power Mod"
lightArmorPowerMod = "Light Armor Power Mod"
pickpocketPowerMod = "Pickpocket Power Mod"
lockpickingPowerMod = "Lockpicking Power Mod"
sneakPowerMod = "Sneak Power Mod"
alchemyPowerMod = "Alchemy Power Mod"
speechPowerMod = "Speech Power Mod"
enchantingPowerMod = "Enchanting Power Mod"
alterationPowerMod = "Alteration Power Mod"
conjurationPowerMod = "Conjuration Power Mod"
destructionPowerMod = "Destruction Power Mod"
illusionPowerMod = "Illusion Power Mod"
restorationPowerMod = "Restoration Power Mod"
speedMult = "Speed"
inventoryWeight = "Inventory Weight"
carryWeight = "Carry Weight"
criticalChance = "Crit. Chance"
meleeDamage = "Melee Damage"
unarmedDamage = "Unarmed Damage"
absorbChance = "Magic Absorb Chance"
weaponSpeedMult = "Weapon Speed"
bowSpeedBonus = "Bow Speed Bonus"
shoutRecoveryMult = "Shout Recovery Multi"
movementNoiseMult = "Noise"
dragonSouls = "Dragon Souls"
combatHealthRegenMultiply = "Combat Health Regen Multi"
attackDamageMult = "Attack Multiplier"
beast = "Beast"
xp = "XP"
reflectDamage = "Reflect Damage"
oneHandedMod = "One Handed Mod"
twoHandedMod = "Two Handed Mod"
archeryMod = "Archery Mod"
blockMod = "Block Mod"
smithingMod = "Smithing Mod"
heavyArmorMod = "Heavy Armor Mod"
lightArmorMod = "Light Armor Mod"
pickpocketMod = "Pickpocket Mod"
lockpickingMod = "Lockpicking Mod"
sneakMod = "Sneak Mod"
alchemyMod = "Alchemy Mod"
speechMod = "Speech Mod"
enchantingMod = "Enchanting Mod"
alterationMod = "Alteration Mod"
conjurationMod = "Conjuration Mod"
destructionMod = "Destruction Mod"
illusionMod = "Illusion Mod"
restorationMod = "Restoration Mod"
damageArrow = "Damage Arrow"
damageLeft = "Damage Weapon Left"
leftWeaponSpeedMult = "Weapon Speed Left"
rightItemCharge = "Item Charge Right"
leftItemCharge = "Item Charge Left"
armorPerks = "Armor rating multiplier"
mass = "Mass"
bowStaggerBonus = "Bow Stagger Bonus"
bypassVendorKeywordCheck = "Vendor any Item"
bypassVendorStolenCheck = "Vendor stolen Item"

[showStatsEnding]
name = ""
race = ""
level = ""
perkCount = ""
height = ""
equipedWeight = ""
weight = ""
armor = ""
damage = ""
skillTrainingsThisLevel = ""
health = ""
healthRatePer = " %"
magicka = ""
magickaRatePer = " %"
stamina = ""
staminaRatePer = " %"
resistDamage = ""
resistDisease = " %"
resistPoison = " %"
resistFire = " %"
resistShock = " %"
resistFrost = " %"
resistMagic = " %"
oneHanded = ""
twoHanded = ""
archery = ""
block = ""
smithing = ""
heavyArmor = ""
lightArmor = ""
pickpocket = ""
lockpicking = ""
sneak = ""
alchemy = ""
speech = ""
enchanting = ""
alteration = ""
conjuration = ""
destruction = ""
illusion = ""
restoration = ""
oneHandedPowerMod = ""
twoHandedPowerMod = ""
archeryPowerMod = ""
blockPowerMod = ""
smithingPowerMod = ""
heavyArmorPowerMod = ""
lightArmorPowerMod = ""
pickpocketPowerMod = ""
lockpickingPowerMod = ""
sneakPowerMod = ""
alchemyPowerMod = ""
speechPowerMod = ""
enchantingPowerMod = ""
alterationPowerMod = ""
conjurationPowerMod = ""
destructionPowerMod = ""
illusionPowerMod = ""
restorationPowerMod = ""
speedMult = " %"
inventoryWeight = ""
carryWeight = ""
criticalChance = " %"
meleeDamage = ""
unarmedDamage = ""
absorbChance = " %"
weaponSpeedMult = "" # should be in %
bowSpeedBonus = ""
shoutRecoveryMult = " %"
movementNoiseMult = " %" # should be in %
dragonSouls = ""
combatHealthRegenMultiply = " %" # should be in %
attackDamageMult = " x" # 
beast = ""
xp = ""
reflectDamage = " %"
oneHandedMod = " %"
twoHandedMod = " %"
archeryMod = " %"
blockMod = " %"
smithingMod = " %"
heavyArmorMod = " %"
lightArmorMod = " %"
pickpocketMod = " %"
lockpickingMod = " %"
sneakMod = " %"
alchemyMod = " %"
speechMod = " %"
enchantingMod = " %"
alterationMod = " %"
conjurationMod = " %"
destructionMod = " %"
illusionMod = " %"
restorationMod = " %"
damageArrow = ""
damageLeft = ""
leftWeaponSpeedMult = "" # should be in %
rightItemCharge = ""
leftItemCharge = ""
armorPerks = " %"
mass = ""
bowStaggerBonus = ""
bypassVendorKeywordCheck = ""
bypassVendorStolenCheck = ""

[showStatsMenu]
height = 1 #player(1),defence(2),attack(3),magic(4),warrior(5),thief(6)
equipedWeight = 1
weight = 1
armor = 2
damage = 3
skillTrainingsThisLevel = 1
health = 2
healthRatePer = 2
magicka = 2
magickaRatePer = 2
stamina = 2
staminaRatePer = 2
resistDamage = 2
resistDisease = 2
resistPoison = 2
resistFire = 2
resistShock = 2
resistFrost = 2
resistMagic = 2
oneHanded = 5
twoHanded = 5
archery = 6
block = 5
smithing = 5
heavyArmor = 5
lightArmor = 5
pickpocket = 6
lockpicking = 6
sneak = 6
alchemy = 6
speech = 6
enchanting = 4
alteration = 4
conjuration = 4
destruction = 4
illusion = 4
restoration = 4
oneHandedPowerMod = 5
twoHandedPowerMod = 5
archeryPowerMod = 6
blockPowerMod = 5
smithingPowerMod = 5
heavyArmorPowerMod = 5
lightArmorPowerMod = 5
pickpocketPowerMod = 6
lockpickingPowerMod = 6
sneakPowerMod = 6
alchemyPowerMod = 6
speechPowerMod = 6
enchantingPowerMod = 4
alterationPowerMod = 4
conjurationPowerMod = 4
destructionPowerMod = 4
illusionPowerMod = 4
restorationPowerMod = 4
speedMult = 1
inventoryWeight = 1
carryWeight = 1
criticalChance = 3
meleeDamage = 3
unarmedDamage = 3
absorbChance = 2
weaponSpeedMult = 3
bowSpeedBonus = 3
shoutRecoveryMult = 1
movementNoiseMult = 1
dragonSouls = 1
combatHealthRegenMultiply = 2
attackDamageMult = 3
reflectDamage = 2
oneHandedMod = 5
twoHandedMod = 5
archeryMod = 6
blockMod = 5
smithingMod = 5
heavyArmorMod = 5
lightArmorMod = 5
pickpocketMod = 6
lockpickingMod = 6
sneakMod = 6
alchemyMod = 6
speechMod = 6
enchantingMod = 4
alterationMod = 4
conjurationMod = 4
destructionMod = 4
illusionMod = 4
restorationMod = 4
damageArrow = 3
damageLeft = 3
leftWeaponSpeedMult = 3
rightItemCharge = 3
leftItemCharge = 3
armorPerks = 2
mass = 1
bowStaggerBonus = 3
bypassVendorKeywordCheck = 1
bypassVendorStolenCheck = 1

[showStatsMultiplier]
weaponSpeedMult = 1 #0 will not work, cause math you know
shoutRecoveryMult = 100
movementNoiseMult = 100
combatHealthRegenMultiply = 100
leftWeaponSpeedMult = 1
armorPerks = 100

[showFactionsFactionNames]
companions = "Companions"
darkbrotherHood = "The Dark Brotherhood"
collegeOfWinterhold = "College of Winterhold"
orcFriend = "Blood-Kin of the Orcs"
thiefsGuild = "Thieves' Guild"
imperialLegion = "Imperial Legion"
stormcloaks = "Stormcloaks" #sons of skyrim
greybeard = "The Greybeards"
bard = "Bards College"
volkiharVampireClan = "Volkihar Vampire Clan"
dawnguard = "Dawnguard"
houseTelvanni = "House Telvanni"

[showFactionsFactionMenu]
companions = 1 #faction(1),thane(2),champion(3)
darkbrotherHood = 1
collegeOfWinterhold = 1
orcFriend = 1
thiefsGuild = 1
imperialLegion = 1
stormcloaks = 1
greybeard = 1
bard = 1
volkiharVampireClan = 1
dawnguard = 1
houseTelvanni = 1

[showFactionsFactionRank]
bard = "Bard"
assassin = "Assassin"
listener = "Listener"
auxiliary = "Auxiliary"
quaestor = "Quaestor"
praefect = "Praefect"
tribune = "Tribune"
legate = "Legate"
unblooded = "Unblooded"
iceVeins = "Ice-Veins"
boneBreaker = "Bone-Breaker"
snowHammer = "Snow-Hammer"
stormblade = "Stormblade"
vampireLord = "Vampire Lord"
vampireHunter = "Vampire Hunter"
honoraryMember = "Honorary Member"
ysmir = "Ysmir"

[showFactionsThaneMenu]
thaneOfEastmarch = 2 #faction(1),thane(2),champion(3)
thaneOfFalkreath = 2
thaneOfHaafingar = 2
thaneOfHjaalmarch = 2
thaneOfThePale = 2
thaneOfTheReach = 2
thaneOfTheRift = 2
thaneOfWhiterun = 2
thaneOfWinterhold = 2

[showFactionsThaneName]
thaneOfEastmarch = "Thane Of Eastmarch"
thaneOfFalkreath = "Thane Of Falkreath"
thaneOfHaafingar = "Thane Of Haafingar"
thaneOfHjaalmarch = "Thane Of Hjaalmarch"
thaneOfThePale = "Thane Of The Pale"
thaneOfTheReach = "Thane Of The Reach"
thaneOfTheRift = "Thane Of The Rift"
thaneOfWhiterun = "Thane Of Whiterun"
thaneOfWinterhold = "Thane Of Winterhold"

[showFactionsChampionMenu]
azura = 3 #faction(1),thane(2),champion(3)
boethiah = 3
clavicusVile = 3
hermaeusMora = 3
hircine = 3
malacath = 3
mehrunesDagon = 3
mephala = 3
meridia = 3
molagBal = 3
namira = 3
nocturnal = 3
peryite = 3
sanguine = 3
sheogorath = 3
vaermina = 3

[showFactionsChampionName]
azura = "Azura"
boethiah = "Boethiah"
clavicusVile = "Clavicus Vile"
hermaeusMora = "Hermaeus Mora"
hircine = "Hircine"
malacath = "Malacath"
mehrunesDagon = "Mehrunes Dagon"
mephala = "Mephala"
meridia = "Meridia"
molagBal = "Molag Bal"
namira = "Namira"
nocturnal = "Nocturnal"
peryite = "Peryite"
sanguine = "Sanguine"
sheogorath = "Sheogorath"
vaermina = "Vaermina"