[General]
logLevel = 1 # 0 trace; 1 debug; 2 info
closeOnEveryButtonPress = false # otherwise menu just closes at ESC and binded key

[showBeastName]
vampire = "Vampire"
werewolf = "Werewolf"

[showStats]
name = true
race = true
level = true
perkCount = true
height = false
equipedWeight = false
weight = true
armor = true
damage = true #might display arrow damage
skillTrainingsThisLevel = true
health = true
healthRatePer = true
magicka = true
magickaRatePer = true
stamina = true
staminaRatePer = true
resistDamage = false #might be the same as armor
resistDisease = true
resistPoison = true
resistFire = true
resistShock = true
resistFrost = true
resistMagic = true
oneHanded = true
twoHanded = true
archery = true
block = true
smithing = true
heavyArmor = true
lightArmor = true
pickpocket = true
lockpicking = true
sneak = true
alchemy = true
speech = true
enchanting = true
alteration = true
conjuration = true
destruction = true
illusion = true
restoration = true
oneHandedPowerMod = false
twoHandedPowerMod = false
archeryPowerMod = false
blockPowerMod = false
smithingPowerMod = false
heavyArmorPowerMod = false
lightArmorPowerMod = false
pickpocketPowerMod = false
lockpickingPowerMod = false
sneakPowerMod = false
alchemyPowerMod = false
speechPowerMod = false
enchantingPowerMod = false
alterationPowerMod = false
conjurationPowerMod = false
destructionPowerMod = false
illusionPowerMod = false
restorationPowerMod = false
speedMult = true
inventoryWeight = true
carryWeight = true
criticalChance = true
meleeDamage = false
unarmedDamage = false
absorbChance = true
weaponSpeedMult = true
bowSpeedBonus = true
shoutRecoveryMult = false
movementNoiseMult = true
dragonSouls = true
combatHealthRegenMultiply = false
attackDamageMult = false
beast = true
xp = true #will not be shown
reflectDamage = false
oneHandedMod = true
twoHandedMod = true
archeryMod = true
blockMod = true
smithingMod = true
heavyArmorMod = true
lightArmorMod = true
pickpocketMod = true
lockpickingMod = true
sneakMod = true
alchemyMod = true
speechMod = true
enchantingMod = true
alterationMod = true
conjurationMod = true
destructionMod = true
illusionMod = true
restorationMod = true
damageArrow = true
damageRight = true
damageLeft = true

[showStatsName]
name = "Name"
race = "Race"
level = "Level"
perkCount = "Open Perks"
height = "Height"
equipedWeight = "Equiped Weight"
weight = "Weight"
armor = "Armor"
damage = "Damage Weapon"
skillTrainingsThisLevel = "Traings This Level"
health = "Health"
healthRatePer = "Health Rate"
magicka = "Magicka"
magickaRatePer = "Magicka Rate"
stamina = "Stamina"
staminaRatePer = "Stamina Rate"
resistDamage = "Resist Damage"
resistDisease = "Resist Disease"
resistPoison = "Resist Poison"
resistFire = "Resist Fire"
resistShock = "Resist Shock"
resistFrost = "Resist Frost"
resistMagic = "Resist Magic"
oneHanded = "One Handed"
twoHanded = "Two Handed"
archery = "Archery"
block = "Block"
smithing = "Smithing"
heavyArmor = "Heavy Armor"
lightArmor = "Light Armor"
pickpocket = "Pickpocket"
lockpicking = "Lockpicking"
sneak = "Sneak"
alchemy = "Alchemy"
speech = "Speech"
enchanting = "Enchanting"
alteration = "Alteration"
conjuration = "Conjuration"
destruction = "Destruction"
illusion = "Illusion"
restoration = "Restoration"
oneHandedPowerMod = "One Handed Power Mod"
twoHandedPowerMod = "Two Handed Power Mod"
archeryPowerMod = "Archery Power Mod"
blockPowerMod = "Block Power Mod"
smithingPowerMod = "Smithing Power Mod"
heavyArmorPowerMod = "Heavy Armor Power Mod"
lightArmorPowerMod = "Light Armor Power Mod"
pickpocketPowerMod = "Pickpocket Power Mod"
lockpickingPowerMod = "Lockpicking Power Mod"
sneakPowerMod = "Sneak Power Mod"
alchemyPowerMod = "Alchemy Power Mod"
speechPowerMod = "Speech Power Mod"
enchantingPowerMod = "Enchanting Power Mod"
alterationPowerMod = "Alteration Power Mod"
conjurationPowerMod = "Conjuration Power Mod"
destructionPowerMod = "Destruction Power Mod"
illusionPowerMod = "Illusion Power Mod"
restorationPowerMod = "Restoration Power Mod"
speedMult = "Speed"
inventoryWeight = "Inventory Weight"
carryWeight = "Carry Weight"
criticalChance = "Crit. Chance"
meleeDamage = "Melee Damage"
unarmedDamage = "Unarmed Damage"
absorbChance = "Magic Absorb"
weaponSpeedMult = "Weapon Speed"
bowSpeedBonus = "Bow Speed Bonus"
shoutRecoveryMult = "Shout Recovery Multi"
movementNoiseMult = "Noise Reduction"
dragonSouls = "Dragon Souls"
combatHealthRegenMultiply = "Combat Health Regen Multi"
attackDamageMult = "Attack Multi"
beast = "Beast"
xp = "" #xp = "XP"
reflectDamage = "Reflect Damage"
oneHandedMod = "One Handed Mod"
twoHandedMod = "Two Handed Mod"
archeryMod = "Archery Mod"
blockMod = "Block Mod"
smithingMod = "Smithing Mod"
heavyArmorMod = "Heavy Armor Mod"
lightArmorMod = "Light Armor Mod"
pickpocketMod = "Pickpocket Mod"
lockpickingMod = "Lockpicking Mod"
sneakMod = "Sneak Mod"
alchemyMod = "Alchemy Mod"
speechMod = "Speech Mod"
enchantingMod = "Enchanting Mod"
alterationMod = "Alteration Mod"
conjurationMod = "Conjuration Mod"
destructionMod = "Destruction Mod"
illusionMod = "Illusion Mod"
restorationMod = "Restoration Mod"
damageArrow = "Damage Arrow"
damageRight = "Damage Weapon Right"
damageLeft = "Damage Weapon Left"

[showStatsEnding]
name = ""
race = ""
level = ""
perkCount = ""
height = ""
equipedWeight = ""
weight = ""
armor = ""
damage = ""
skillTrainingsThisLevel = ""
health = ""
healthRatePer = " %"
magicka = ""
magickaRatePer = " %"
stamina = ""
staminaRatePer = ""
resistDamage = ""
resistDisease = " %"
resistPoison = " %"
resistFire = " %"
resistShock = " %"
resistFrost = " %"
resistMagic = " %"
oneHanded = ""
twoHanded = ""
archery = ""
block = ""
smithing = ""
heavyArmor = ""
lightArmor = ""
pickpocket = ""
lockpicking = ""
sneak = ""
alchemy = ""
speech = ""
enchanting = ""
alteration = ""
conjuration = ""
destruction = ""
illusion = ""
restoration = ""
oneHandedPowerMod = ""
twoHandedPowerMod = ""
archeryPowerMod = ""
blockPowerMod = ""
smithingPowerMod = ""
heavyArmorPowerMod = ""
lightArmorPowerMod = ""
pickpocketPowerMod = ""
lockpickingPowerMod = ""
sneakPowerMod = ""
alchemyPowerMod = ""
speechPowerMod = ""
enchantingPowerMod = ""
alterationPowerMod = ""
conjurationPowerMod = ""
destructionPowerMod = ""
illusionPowerMod = ""
restorationPowerMod = ""
speedMult = ""
inventoryWeight = ""
carryWeight = ""
criticalChance = ""
meleeDamage = ""
unarmedDamage = ""
absorbChance = ""
weaponSpeedMult = ""
bowSpeedBonus = ""
shoutRecoveryMult = ""
movementNoiseMult = " %"
dragonSouls = ""
combatHealthRegenMultiply = ""
attackDamageMult = ""
beast = ""
xp = ""
reflectDamage = ""
oneHandedMod = " %"
twoHandedMod = " %"
archeryMod = " %"
blockMod = " %"
smithingMod = " %"
heavyArmorMod = " %"
lightArmorMod = " %"
pickpocketMod = " %"
lockpickingMod = " %"
sneakMod = " %"
alchemyMod = " %"
speechMod = " %"
enchantingMod = " %"
alterationMod = " %"
conjurationMod = " %"
destructionMod = " %"
illusionMod = " %"
restorationMod = " %"
damageArrow = ""
damageRight = ""
damageLeft = ""